import { describe, expect, it, vi } from "vitest";
import { KairosService } from "../src/kairos/kairos.service";
import { favoriteSchema } from "../src/kairos/kairos.schemas";
import { projectUpdateSchema } from "../src/kairos/kairos.schemas";
import { ZodValidationPipe } from "../src/common/validation/zod-validation.pipe";
import { z } from "zod";
import { PositiveIntPipe } from "../src/common/validation/positive-int.pipe";
import { EstadoProyectoKairos, EstadoUsuario, RolMiembroProyectoKairos, RolUsuario } from "../src/generated/prisma/enums";
import type { AuthUser } from "../src/auth/auth-user";

const actor = (id = 1, rol: RolUsuario = RolUsuario.COORDINADOR, estado: EstadoUsuario = EstadoUsuario.ACTIVA, areaId: number | null = 10, sedeId: number | null = 20): AuthUser => ({ id, codigo: `U${id}`, email: `${id}@test.local`, rol, estado, areaId, sedeId, turnoId: null });
const project = { id: "p-1", nombre: "Proyecto", descripcion: null, estado: EstadoProyectoKairos.BORRADOR, prioridad: "MEDIA", creadoPorId: 1, createdAt: new Date(), updatedAt: new Date() };
const member = (rol: RolMiembroProyectoKairos = RolMiembroProyectoKairos.PROPIETARIO, usuarioId = 1, removedAt: Date | null = null): { proyectoId: string; usuarioId: number; rol: RolMiembroProyectoKairos; removedAt: Date | null } => ({ proyectoId: "p-1", usuarioId, rol, removedAt });

function tx(overrides: any = {}) {
  const base: any = {
    $executeRaw: vi.fn(),
    auditEvent: { create: vi.fn().mockResolvedValue({}) },
    proyectoKairos: { create: vi.fn().mockResolvedValue(project), update: vi.fn().mockResolvedValue(project), findUnique: vi.fn().mockResolvedValue({ estado: EstadoProyectoKairos.ACTIVO }) },
    miembroProyectoKairos: { create: vi.fn().mockResolvedValue(member()), findUnique: vi.fn().mockResolvedValue(member()), findFirst: vi.fn().mockResolvedValue(member()), count: vi.fn().mockResolvedValue(2), update: vi.fn().mockResolvedValue(member()) },
    usuario: { findUnique: vi.fn().mockResolvedValue({ id: 2, estado: EstadoUsuario.ACTIVA }) },
    favoritoProyectoKairos: { upsert: vi.fn().mockResolvedValue({}), deleteMany: vi.fn().mockResolvedValue({ count: 1 }) },
  };
  return { ...base, ...overrides, proyectoKairos: { ...base.proyectoKairos, ...overrides.proyectoKairos }, miembroProyectoKairos: { ...base.miembroProyectoKairos, ...overrides.miembroProyectoKairos }, auditEvent: { ...base.auditEvent, ...overrides.auditEvent }, usuario: { ...base.usuario, ...overrides.usuario }, favoritoProyectoKairos: { ...base.favoritoProyectoKairos, ...overrides.favoritoProyectoKairos } };
}
function service(overrides: any = {}) {
  const db: any = {
    $transaction: vi.fn((fn: any) => { const transaction = tx(overrides.tx); db.__lastTx = transaction; return fn(transaction); }),
    miembroProyectoKairos: { findFirst: vi.fn().mockResolvedValue(member()) },
    usuario: { findUnique: vi.fn().mockResolvedValue({ id: 2, estado: EstadoUsuario.ACTIVA }) },
    proyectoKairos: { findMany: vi.fn().mockResolvedValue([]), count: vi.fn().mockResolvedValue(0), findUnique: vi.fn().mockResolvedValue({ ...project, miembros: [], favoritos: [] }) },
    favoritoProyectoKairos: { upsert: vi.fn().mockResolvedValue({}), deleteMany: vi.fn().mockResolvedValue({ count: 1 }) },
    ...overrides,
  };
  return { s: new KairosService(db), db };
}

describe("KairosService project lifecycle", () => {
  it.each(["abc", "0", "-1", "1.5"]) ("rejects invalid controller integer query/route value %s with 400", (value) => { expect(() => new PositiveIntPipe().transform(value)).toThrow(expect.objectContaining({ status: 400 })); });
  it("rejects string booleans for the favorite controller body", () => { expect(() => favoriteSchema.parse({ enabled: "true" })).toThrow(); expect(favoriteSchema.parse({ enabled: true })).toEqual({ enabled: true }); });
  it.each(["abc", "1"]) ("rejects invalid favorite query %s through the controller query validation pipe", (value) => { const pipe = new ZodValidationPipe(z.enum(["true", "false"]).optional()); expect(() => pipe.transform(value)).toThrow(expect.objectContaining({ status: 400 })); });
  it("rejects an empty project update body through the controller validation pipe", () => { const pipe = new ZodValidationPipe(projectUpdateSchema); expect(() => pipe.transform({})).toThrow(expect.objectContaining({ status: 400 })); });
  it("creates a project and exactly one owner in one transaction", async () => {
    const { s, db } = service(); const result = await s.create(actor(), { nombre: "X", prioridad: "ALTA" });
    expect(result).toEqual(project); expect(db.$transaction).toHaveBeenCalled();
    const create = db.$transaction.mock.calls[0][0]; const t = tx(); await create(t);
    expect(t.proyectoKairos.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ creadoPorId: 1, miembros: { create: { usuarioId: 1, rol: RolMiembroProyectoKairos.PROPIETARIO } } }) }));
    expect(t.auditEvent.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "CREATE", resource: "KAIROS_PROJECT" }) }));
  });
  it.each([RolUsuario.PRESTADOR])("rejects create for role without project-create grant (%s)", async (rol) => { await expect(service().s.create(actor(1, rol), { nombre: "X" })).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("rejects create for inactive actor without enumeration", async () => { await expect(service().s.create(actor(1, RolUsuario.ADMIN, EstadoUsuario.SUSPENDIDA), { nombre: "X" })).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("allows sede and global project creators", async () => { await expect(service().s.create(actor(1, RolUsuario.JEFE_SEDE), { nombre: "S" })).resolves.toBe(project); await expect(service().s.create(actor(1, RolUsuario.ADMIN), { nombre: "G" })).resolves.toBe(project); });
  it("lists only active memberships with favorite projection", async () => {
    const item = { ...project, miembros: [{ rol: RolMiembroProyectoKairos.SUBLIDER }], favoritos: [{ proyectoId: "p-1" }] }; const { s, db } = service({ proyectoKairos: { findMany: vi.fn().mockResolvedValue([item]), count: vi.fn().mockResolvedValue(1) } });
    const result = await s.list(actor(), 2, 10, "abc", true); expect(result.items[0]).toMatchObject({ rol: RolMiembroProyectoKairos.SUBLIDER, favorito: true }); expect(result.items[0].miembros).toBeUndefined(); expect(db.proyectoKairos.findMany.mock.calls[0][0].where).toMatchObject({ miembros: { some: { usuarioId: 1, removedAt: null } }, nombre: { contains: "abc" }, favoritos: { some: { usuarioId: 1 } } }); expect(result).toMatchObject({ page: 2, pageSize: 10, total: 1 });
  });
  it("clamps list pagination and does not enumerate inactive actor", async () => { const { s, db } = service(); await expect(s.list({ ...actor(), estado: EstadoUsuario.BLOQUEADA })).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); await s.list(actor(), 0, 1000); expect(db.proyectoKairos.findMany.mock.calls[0][0]).toMatchObject({ skip: 0, take: 100 }); });
  it("gets inside a transaction, locks membership, filters inactive users, and omits email", async () => { const detail = { ...project, miembros: [{ usuarioId: 1, rol: RolMiembroProyectoKairos.PROPIETARIO, usuario: { id: 1, codigo: "U1" } }], favoritos: [] }; const { s, db } = service({ tx: { proyectoKairos: { findUnique: vi.fn().mockResolvedValue(detail) } } }); const result = await s.get(actor(), "p-1"); expect(result).toMatchObject({ id: "p-1", rol: RolMiembroProyectoKairos.PROPIETARIO, favorito: false }); expect(result.miembros[0].usuario).not.toHaveProperty("email"); expect(db.__lastTx.$executeRaw).toHaveBeenCalledTimes(2); expect(db.__lastTx.proyectoKairos.findUnique.mock.calls[0][0].select.miembros.where).toEqual({ removedAt: null, usuario: { estado: EstadoUsuario.ACTIVA } }); });
  it("does not enumerate a non-member on get", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findFirst: vi.fn().mockResolvedValue(null) }, proyectoKairos: { findUnique: vi.fn().mockResolvedValue({ ...project, miembros: [], favoritos: [] }) } } }); await expect(s.get(actor(), "secret")).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("updates only for owner or subleader and locks project", async () => { const { s } = service({ miembroProyectoKairos: { findFirst: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.SUBLIDER)) } }); const result = await s.update(actor(), "p-1", { nombre: "Nuevo" }); expect(result).toBe(project); const t = tx(); await t.proyectoKairos.update; expect(t.$executeRaw).toBeDefined(); });
  it.each([RolMiembroProyectoKairos.COLABORADOR, RolMiembroProyectoKairos.OBSERVADOR])("does not allow %s to update", async (rol) => { const { s } = service({ tx: { miembroProyectoKairos: { findFirst: vi.fn().mockResolvedValue(member(rol)) } } }); await expect(s.update(actor(), "p-1", { nombre: "N" })).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("archives through the update transaction", async () => { const { s, db } = service(); await expect(s.archive(actor(), "p-1")).resolves.toBe(project); expect(db.$transaction).toHaveBeenCalled(); });
  it("adds an active member and audits the operation", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(null) } } }); const result = await s.addMember(actor(), "p-1", 2, RolMiembroProyectoKairos.COLABORADOR); expect(result).toEqual(member()); });
  it("rejects inactive member targets", async () => { const { s } = service({ tx: { usuario: { findUnique: vi.fn().mockResolvedValue({ id: 2, estado: EstadoUsuario.SUSPENDIDA }) }, miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(null) } } }); await expect(s.addMember(actor(), "p-1", 2, RolMiembroProyectoKairos.COLABORADOR)).rejects.toMatchObject({ code: "KAIROS_MEMBER_INVALID" }); });
  it("preserves a duplicate constraint error from Prisma", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(null), create: vi.fn().mockRejectedValue({ code: "P2002" }) } } }); await expect(s.addMember(actor(), "p-1", 2, RolMiembroProyectoKairos.COLABORADOR)).rejects.toMatchObject({ code: "P2002" }); });
  it("rejects direct promotion to owner and requires transfer", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.COLABORADOR, 2)) } } }); await expect(s.changeRole(actor(), "p-1", 2, RolMiembroProyectoKairos.PROPIETARIO)).rejects.toMatchObject({ code: "KAIROS_TRANSFER_REQUIRED" }); });
  it("changes a member role with a row lock", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.COLABORADOR, 2)), update: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.SUBLIDER, 2)) } } }); const result = await s.changeRole(actor(), "p-1", 2, RolMiembroProyectoKairos.SUBLIDER); expect(result.rol).toBe(RolMiembroProyectoKairos.SUBLIDER); });
  it("rejects direct owner role changes and requires transfer", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.PROPIETARIO, 2)) } } }); await expect(s.changeRole(actor(), "p-1", 2, RolMiembroProyectoKairos.SUBLIDER)).rejects.toMatchObject({ code: "KAIROS_TRANSFER_REQUIRED" }); });
  it("transfers ownership atomically from owner to target", async () => { const update = vi.fn().mockResolvedValue(member()); const findFirst = vi.fn().mockResolvedValueOnce(member(RolMiembroProyectoKairos.PROPIETARIO, 1)).mockResolvedValueOnce(member(RolMiembroProyectoKairos.COLABORADOR, 2)); const { s, db } = service({ tx: { miembroProyectoKairos: { findFirst, update } } }); await s.transferOwnership(actor(), "p-1", 2); expect(update).toHaveBeenCalledTimes(2); expect(update.mock.calls[0][0].data).toEqual({ rol: RolMiembroProyectoKairos.SUBLIDER }); expect(update.mock.calls[1][0].data).toEqual({ rol: RolMiembroProyectoKairos.PROPIETARIO }); expect(db.__lastTx.auditEvent.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "TRANSFER_OWNERSHIP" }) })); });
  it("returns member-not-found for role changes outside the project", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(null) } } }); await expect(s.changeRole(actor(), "p-1", 99, RolMiembroProyectoKairos.COLABORADOR)).rejects.toMatchObject({ code: "KAIROS_MEMBER_NOT_FOUND" }); });
  it("removes a collaborator logically and keeps audit in transaction", async () => { const update = vi.fn().mockResolvedValue({ ...member(RolMiembroProyectoKairos.COLABORADOR, 2), removedAt: new Date() }); const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.COLABORADOR, 2)), update } } }); const result = await s.removeMember(actor(), "p-1", 2); expect(result.removedAt).toBeInstanceOf(Date); expect(update.mock.calls[0][0].data).toEqual(expect.objectContaining({ removedAt: expect.any(Date) })); });
  it("protects the last owner from removal", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.PROPIETARIO, 2)), count: vi.fn().mockResolvedValue(1) } } }); await expect(s.removeMember(actor(), "p-1", 2)).rejects.toMatchObject({ code: "KAIROS_OWNER_REQUIRED" }); });
  it("rejects removal of missing or already removed member", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.COLABORADOR, 2, new Date())) } } }); await expect(s.removeMember(actor(), "p-1", 2)).rejects.toMatchObject({ code: "KAIROS_MEMBER_NOT_FOUND" }); });
  it("favorites idempotently with upsert and transaction audit", async () => { const { s, db } = service(); await expect(s.favorite(actor(), "p-1", true)).resolves.toEqual({ id: "p-1", favorito: true }); await s.favorite(actor(), "p-1", true); expect(db.__lastTx.favoritoProyectoKairos.upsert).toHaveBeenCalled(); expect(db.__lastTx.auditEvent.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "FAVORITE" }) })); });
  it("unfavorites by scoped deleteMany and is idempotent", async () => { const { s, db } = service(); await expect(s.favorite(actor(), "p-1", false)).resolves.toEqual({ id: "p-1", favorito: false }); await s.favorite(actor(), "p-1", false); expect(db.__lastTx.favoritoProyectoKairos.deleteMany).toHaveBeenCalledWith(expect.objectContaining({ where: { proyectoId: "p-1", usuarioId: 1 } })); });
  it("does not favorite a non-member or inactive actor", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findFirst: vi.fn().mockResolvedValue(null) } } }); await expect(s.favorite(actor(), "p-1", true)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); const inactive = service(); await expect(inactive.s.favorite({ ...actor(), estado: EstadoUsuario.DESACTIVADA }, "p-1", true)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("uses a transaction for updates and keeps audit metadata redacted", async () => { const audit = vi.fn().mockResolvedValue({}); const { s } = service({ tx: { auditEvent: { create: audit } } }); await s.update(actor(), "p-1", { descripcion: "safe" }); expect(audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ metadata: undefined }) })); });
  it("propagates non-unique Prisma errors instead of masking them", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(null), create: vi.fn().mockRejectedValue({ code: "P2025" }) } } }); await expect(s.addMember(actor(), "p-1", 2, RolMiembroProyectoKairos.COLABORADOR)).rejects.toMatchObject({ code: "P2025" }); });
  it("uses active membership for authorization and excludes removed membership", async () => { const findFirst = vi.fn().mockResolvedValue(null); const { s } = service({ tx: { miembroProyectoKairos: { findFirst } } }); await expect(s.update(actor(), "p-1", { nombre: "N" })).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); expect(findFirst.mock.calls[0][0].where).toEqual({ proyectoId: "p-1", usuarioId: 1, removedAt: null }); });
  it("passes actor scope through list queries without cross-user leakage", async () => { const { s, db } = service(); await s.list(actor(7, RolUsuario.JEFE_SEDE, EstadoUsuario.ACTIVA, null, 20), 1, 20); expect(db.proyectoKairos.findMany.mock.calls[0][0].where.miembros.some).toEqual({ usuarioId: 7, removedAt: null }); });
  it("reactivates a removed member without creating a duplicate and audits it", async () => { const update = vi.fn().mockResolvedValue({ ...member(RolMiembroProyectoKairos.COLABORADOR, 2), removedAt: null }); const { s, db } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.COLABORADOR, 2, new Date())), update } } }); await s.addMember(actor(), "p-1", 2, RolMiembroProyectoKairos.OBSERVADOR); expect(update.mock.calls[0][0].data).toEqual({ rol: RolMiembroProyectoKairos.OBSERVADOR, removedAt: null }); expect(db.__lastTx.auditEvent.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "REACTIVATE_MEMBER" }) })); });
  it("rejects role changes for removed members", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.COLABORADOR, 2, new Date())) } } }); await expect(s.changeRole(actor(), "p-1", 2, RolMiembroProyectoKairos.OBSERVADOR)).rejects.toMatchObject({ code: "KAIROS_MEMBER_NOT_FOUND" }); });
  it("does not remove an owner even when another owner exists", async () => { const { s } = service({ tx: { miembroProyectoKairos: { findUnique: vi.fn().mockResolvedValue(member(RolMiembroProyectoKairos.PROPIETARIO, 2)) } } }); await expect(s.removeMember(actor(), "p-1", 2)).rejects.toMatchObject({ code: "KAIROS_OWNER_REQUIRED" }); });
  it("only the current owner can transfer ownership", async () => { const findFirst = vi.fn().mockResolvedValueOnce(member(RolMiembroProyectoKairos.SUBLIDER, 1)).mockResolvedValueOnce(member(RolMiembroProyectoKairos.COLABORADOR, 2)); const { s } = service({ tx: { miembroProyectoKairos: { findFirst } } }); await expect(s.transferOwnership(actor(), "p-1", 2)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("rejects every mutating operation on archived projects", async () => { const archived = { estado: EstadoProyectoKairos.ARCHIVADO }; const overrides = { tx: { proyectoKairos: { findUnique: vi.fn().mockResolvedValue(archived) } } }; const { s } = service(overrides); await expect(s.update(actor(), "p-1", { nombre: "x" })).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); await expect(s.addMember(actor(), "p-1", 2, RolMiembroProyectoKairos.COLABORADOR)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); await expect(s.changeRole(actor(), "p-1", 2, RolMiembroProyectoKairos.OBSERVADOR)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); await expect(s.transferOwnership(actor(), "p-1", 2)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); await expect(s.removeMember(actor(), "p-1", 2)).rejects.toMatchObject({ code: "KAIROS_PROJECT_NOT_FOUND" }); });
  it("allows reading an archived project for an active member", async () => { const { s } = service({ tx: { proyectoKairos: { findUnique: vi.fn().mockResolvedValue({ ...project, estado: EstadoProyectoKairos.ARCHIVADO, miembros: [], favoritos: [] }) } } }); await expect(s.get(actor(), "p-1")).resolves.toMatchObject({ estado: EstadoProyectoKairos.ARCHIVADO }); });
  it("locks project and actor membership before update", async () => { const { s, db } = service(); await s.update(actor(), "p-1", { nombre: "locked" }); expect(db.__lastTx.$executeRaw).toHaveBeenCalledTimes(2); });
  it("locks project, actor, and target before transfer", async () => { const findFirst = vi.fn().mockResolvedValueOnce(member(RolMiembroProyectoKairos.PROPIETARIO, 1)).mockResolvedValueOnce(member(RolMiembroProyectoKairos.COLABORADOR, 2)); const { s, db } = service({ tx: { miembroProyectoKairos: { findFirst } } }); await s.transferOwnership(actor(), "p-1", 2); expect(db.__lastTx.$executeRaw).toHaveBeenCalledTimes(3); });
  it("uses the safe page ceiling for high pagination inputs", async () => { const { s, db } = service(); const result = await s.list(actor(), 999999, 999999); expect(result.page).toBe(10000); expect(db.proyectoKairos.findMany.mock.calls[0][0]).toMatchObject({ skip: 999900, take: 100 }); });
});
