import { describe, expect, it, vi } from "vitest";
import { InvitationsService } from "../../../src/invitations/invitations.service";
import { RolUsuario } from "../../../src/generated/prisma/enums";

const actor: any = { id: 1, rol: RolUsuario.ADMIN, sedeId: null, areaId: null, turnoId: null };
const invitation: any = { id: "inv-1", targetEmail: "new@example.com", role: RolUsuario.PRESTADOR, sedeId: null, areaId: null, turnoId: null, expiresAt: new Date(Date.now() + 3600000), usedAt: null, revokedAt: null };
function deps(overrides: any = {}) {
  const tx: any = { invitation: { findUnique: vi.fn().mockResolvedValue(invitation), updateMany: vi.fn().mockResolvedValue({ count: 1 }), update: vi.fn().mockResolvedValue(invitation) }, usuario: { create: vi.fn().mockResolvedValue({ id: 8, email: invitation.targetEmail }) } };
  const prisma: any = { invitation: { findUnique: vi.fn().mockResolvedValue(invitation), create: vi.fn().mockResolvedValue(invitation), updateMany: vi.fn().mockResolvedValue({ count: 1 }) }, area: { findUnique: vi.fn().mockResolvedValue(null) }, turno: { findUnique: vi.fn().mockResolvedValue(null) }, $transaction: vi.fn(async (fn: any) => fn(tx)), ...overrides };
  const policy: any = { requireCreation: vi.fn() }; const outbox: any = { enqueue: vi.fn().mockResolvedValue({}) }; const audit: any = { append: vi.fn().mockResolvedValue({}) };
  return { service: new InvitationsService(prisma, outbox, policy, audit), prisma, tx, policy, outbox, audit };
}

describe("InvitationsService security and transactions", () => {
  it("rejects expiry in the past and beyond 72 hours", async () => { const { service } = deps(); await expect(service.create({ targetEmail: "a@b.com", role: RolUsuario.PRESTADOR, actor, expiresAt: new Date(Date.now() - 1) })).rejects.toMatchObject({ code: "INVITATION_EXPIRY_INVALID" }); await expect(service.create({ targetEmail: "a@b.com", role: RolUsuario.PRESTADOR, actor, expiresAt: new Date(Date.now() + 73 * 3600000) })).rejects.toMatchObject({ code: "INVITATION_EXPIRY_INVALID" }); });
  it("delegates role and scope escalation rejection to policy", async () => { const { service, policy } = deps(); policy.requireCreation.mockImplementation(() => { throw new Error("FORBIDDEN"); }); await expect(service.create({ targetEmail: "a@b.com", role: RolUsuario.ADMIN, actor })).rejects.toThrow("FORBIDDEN"); expect(policy.requireCreation).toHaveBeenCalled(); });
  it("rejects inconsistent area and sede placement", async () => { const { service, prisma } = deps(); prisma.area.findUnique.mockResolvedValue({ id: 2, sedeId: 9 }); await expect(service.create({ targetEmail: "a@b.com", role: RolUsuario.PRESTADOR, actor, sedeId: 1, areaId: 2 })).rejects.toMatchObject({ code: "INVITATION_PLACEMENT_INVALID" }); });
  it("maps duplicate token/email conflicts but preserves infrastructure errors", async () => { const duplicate = deps({ $transaction: vi.fn().mockRejectedValue({ code: "P2002" }) }); await expect(duplicate.service.create({ targetEmail: "a@b.com", role: RolUsuario.PRESTADOR, actor })).rejects.toMatchObject({ code: "INVITATION_DUPLICATE" }); const failure = deps({ $transaction: vi.fn().mockRejectedValue(new Error("db down")) }); await expect(failure.service.create({ targetEmail: "a@b.com", role: RolUsuario.PRESTADOR, actor })).rejects.toThrow("db down"); });
  it.each(["expired", "revoked", "used"])("rejects %s invitation acceptance", async (state) => { const { service, tx } = deps(); tx.invitation.findUnique.mockResolvedValue({ ...invitation, ...(state === "expired" ? { expiresAt: new Date(Date.now() - 1) } : state === "revoked" ? { revokedAt: new Date() } : { usedAt: new Date() }) }); await expect(service.accept("raw-token", "hash", "CODE")).rejects.toMatchObject({ code: "INVITATION_INVALID" }); });
  it("allows only one concurrent acceptance", async () => { const { service, tx } = deps(); tx.invitation.updateMany.mockResolvedValueOnce({ count: 1 }).mockResolvedValueOnce({ count: 0 }); const first = service.accept("same", "hash", "C1"); const second = service.accept("same", "hash", "C2"); await expect(first).resolves.toEqual({ id: 8, email: invitation.targetEmail }); await expect(second).rejects.toThrow(); });
  it("rolls back acceptance when audit/outbox fails", async () => { const { service, prisma, outbox } = deps(); outbox.enqueue.mockRejectedValue(new Error("outbox failure")); await expect(service.accept("raw", "hash", "C1")).rejects.toThrow("outbox failure"); expect(prisma.$transaction).toHaveBeenCalled(); });
  it("rejects duplicate codigo/email at database boundary", async () => { const { service, tx } = deps(); tx.usuario.create.mockRejectedValue({ code: "P2002" }); await expect(service.accept("raw", "hash", "C1")).rejects.toMatchObject({ code: "P2002" }); });
  it("requires actor scope for revoke", async () => { const { service, policy } = deps(); policy.requireCreation.mockImplementation(() => { throw new Error("FORBIDDEN"); }); await expect(service.revoke("inv-1", actor)).rejects.toThrow("FORBIDDEN"); });
});
