CREATE TABLE `ReporteExportacion` (
  `id` VARCHAR(30) NOT NULL,
  `requesterId` INTEGER NOT NULL,
  `type` ENUM('ATTENDANCE','DOCUMENTS','KAIROS') NOT NULL,
  `filters` JSON NOT NULL,
  `totalFilas` INTEGER NOT NULL DEFAULT 0,
  `archivoId` VARCHAR(30) NULL,
  `status` ENUM('PENDIENTE','GENERANDO','COMPLETADO','FALLIDO','EXPIRADO') NOT NULL DEFAULT 'PENDIENTE',
  `leaseOwner` VARCHAR(80) NULL,
  `leaseUntil` DATETIME(3) NULL,
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `nextAttemptAt` DATETIME(3) NULL,
  `errorCode` VARCHAR(100) NULL,
  `expiresAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ReporteExportacion_archivoId_key` (`archivoId`),
  KEY `ReporteExportacion_requesterId_createdAt_idx` (`requesterId`,`createdAt`),
  KEY `ReporteExportacion_status_leaseUntil_createdAt_idx` (`status`,`leaseUntil`,`createdAt`),
  KEY `ReporteExportacion_status_nextAttemptAt_createdAt_idx` (`status`,`nextAttemptAt`,`createdAt`),
  KEY `ReporteExportacion_expiresAt_status_idx` (`expiresAt`,`status`),
  CONSTRAINT `ReporteExportacion_requesterId_fkey` FOREIGN KEY (`requesterId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ReporteExportacion_archivoId_fkey` FOREIGN KEY (`archivoId`) REFERENCES `Archivo`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
