import { describe, expect, it, vi } from "vitest";
import { Readable } from "node:stream";
import { StorageService } from "../../../src/storage/storage.service";
import { StorageWorker } from "../../../src/storage/storage.worker";
import { StorageReconciler } from "../../../src/storage/storage.reconciler";
const pdf = Buffer.from("%PDF-1.7\n%%EOF");
const cfg = (max = 1000) => ({ get: (k: string) => k === "STORAGE_MAX_BYTES" ? max : k === "STORAGE_MAX_ATTEMPTS" ? 1 : k === "STORAGE_WORKER_INTERVAL_MS" ? 10 : false }) as never;
const f = () => ({ id: "f", objectKey: "k", quarantineKey: "k", status: "ANALIZANDO", leaseOwner: "owner", leaseUntil: new Date(Date.now() + 60000) });
const analysis = { analisisArchivo: { create: vi.fn() } };
describe("Storage regressions", () => {
  it("rejects over-limit streams before persistence", async () => { const create = vi.fn(); const s = new StorageService({ archivo: { create } } as never, {} as never, {} as never, cfg()); async function* body() { yield Buffer.alloc(700); yield Buffer.alloc(400); } await expect(s.receive({ originalName: "x.pdf", body: body() })).rejects.toThrow(); expect(create).not.toHaveBeenCalled(); });
  it("rejects MIME mismatch", async () => { const s = new StorageService({ archivo: { create: vi.fn() } } as never, {} as never, {} as never, cfg()); await expect(s.receive({ originalName: "x.pdf", contentType: "image/jpeg", body: pdf })).rejects.toThrow(); });
  it("rejects invalid UTF-8 and accepts valid UTF-8 text", async () => { const s = new StorageService({ archivo: { create: vi.fn().mockResolvedValue({ id: "x" }) } } as never, { put: vi.fn() } as never, {} as never, cfg()); await expect(s.receive({ originalName: "x.txt", contentType: "text/plain", body: Buffer.from([0xc3, 0x28]) })).rejects.toThrow(); await expect(s.receive({ originalName: "x.txt", contentType: "text/plain", body: Buffer.from("á\n") })).resolves.toEqual({ id: "x" }); });
  it("accepts ASCII STL and rejects invalid binary STL", async () => { const good = Buffer.from("solid c\n facet normal 0 0 1\n  outer loop\n   vertex 0 0 0\n   vertex 1 0 0\n   vertex 0 1 0\n  endloop\n endfacet\nendsolid c"); const bad = Buffer.alloc(84); bad.writeUInt32LE(1, 80); const s = new StorageService({ archivo: { create: vi.fn().mockResolvedValue({ id: "x" }) } } as never, { put: vi.fn() } as never, {} as never, cfg()); await expect(s.receive({ originalName: "x.stl", contentType: "model/stl", body: good })).resolves.toBeTruthy(); await expect(s.receive({ originalName: "x.stl", contentType: "model/stl", body: bad })).rejects.toThrow(); });
  it("marks max-attempt jobs terminal", async () => { const updateMany = vi.fn().mockResolvedValue({ count: 0 }); const p = { archivo: { updateMany, findMany: vi.fn().mockResolvedValue([{ id: "f" }]) } }; await expect(new StorageWorker(p as never, { analyze: vi.fn() } as never, cfg() as never).processDue()).resolves.toBe(0); expect(updateMany).toHaveBeenCalledTimes(3); });
  it("isolates overlapping scheduler ticks", async () => { let release!: (v?: unknown) => void; const analyze = vi.fn(() => new Promise(r => { release = r; })); const updateMany = vi.fn().mockResolvedValue({ count: 1 }); const p = { archivo: { updateMany, findMany: vi.fn().mockResolvedValue([{ id: "f" }]) } }; const w = new StorageWorker(p as never, { analyze } as never, cfg(1000) as never); const one = w.processDue(); await expect(w.processDue()).resolves.toBe(0); release(); await one; expect(analyze).toHaveBeenCalledTimes(1); });
  it("does not finalize a lost lease", async () => { const updateMany = vi.fn().mockResolvedValue({ count: 0 }); const p = { archivo: { findUnique: vi.fn().mockResolvedValue(f()), updateMany }, ...analysis }; const s = new StorageService(p as never, { get: vi.fn().mockResolvedValue(Readable.from([Buffer.from("x")])), copy: vi.fn(), delete: vi.fn() } as never, { scan: vi.fn().mockResolvedValue({ clean: true }) } as never, cfg()); await s.analyze("f", "owner"); expect(updateMany).toHaveBeenCalled(); });
  it("recovers when quarantine deletion fails", async () => { const updateMany = vi.fn().mockResolvedValue({ count: 1 }); const p = { archivo: { findUnique: vi.fn().mockResolvedValue(f()), updateMany }, ...analysis }; const storage = { get: vi.fn().mockResolvedValue(Readable.from([Buffer.from("x")])), copy: vi.fn(), delete: vi.fn().mockRejectedValue(new Error("delete")) }; await expect(new StorageService(p as never, storage as never, { scan: vi.fn().mockResolvedValue({ clean: true }) } as never, cfg()).analyze("f", "owner")).resolves.toBeTruthy(); expect(storage.copy).toHaveBeenCalled(); });
  it("compensates when promotion update loses lease", async () => { const updateMany = vi.fn().mockResolvedValue({ count: 0 }); const p = { archivo: { findUnique: vi.fn().mockResolvedValue(f()), updateMany }, ...analysis }; const storage = { get: vi.fn().mockResolvedValue(Readable.from([Buffer.from("x")])), copy: vi.fn(), delete: vi.fn() }; await new StorageService(p as never, storage as never, { scan: vi.fn().mockResolvedValue({ clean: true }) } as never, cfg()).analyze("f", "owner"); expect(storage.delete).toHaveBeenCalledWith("available", "k"); });
  it("rejects a capability for another resource", async () => { const s = new StorageService({ archivo: { findUnique: vi.fn() } } as never, {} as never, {} as never, cfg()); await expect(s.downloadUrl("f", { subjectId: "u", resourceId: "other", purpose: "download", issuedAt: new Date() } as never, "u")).rejects.toThrow(); });
});
describe("Reconciler regressions", () => {
  it("loads references beyond batch and uses independent cursors", async () => { const p = { archivo: { findMany: vi.fn().mockResolvedValueOnce([{ id: "f", objectKey: "known", quarantineKey: "q", status: "DISPONIBLE", updatedAt: new Date() }]).mockResolvedValueOnce([{ objectKey: "far", quarantineKey: "q2" }]), update: vi.fn() } }; const list = vi.fn().mockResolvedValue({ objects: [], nextCursor: undefined }); await new StorageReconciler(p as never, { head: vi.fn().mockResolvedValue(false), list, delete: vi.fn() } as never, { get: () => 1 } as never).run(1); expect(p.archivo.findMany).toHaveBeenCalledTimes(2); });
  it("isolates head and list failures", async () => { const list = vi.fn().mockRejectedValue(new Error("offline")); const p = { archivo: { findMany: vi.fn().mockResolvedValue([]), update: vi.fn() } }; await expect(new StorageReconciler(p as never, { head: vi.fn().mockRejectedValue(new Error("head")), list } as never, { get: () => 1 } as never).run()).resolves.toMatchObject({ inspected: 0 }); expect(list).toHaveBeenCalled(); });
});
