import { Injectable } from "@nestjs/common";
import { PrismaService } from "../database/prisma.service";
import { conflict, invalidInput, notFound } from "../common/errors/domain-error";
import { Permission, getAccessScope } from "../auth/permissions";
import type { AuthUser } from "../auth/auth-user";
import type { ProjectInput, ProjectUpdate } from "./kairos.schemas";
import { EstadoProyectoKairos, EstadoUsuario, RolMiembroProyectoKairos } from "../generated/prisma/enums";

const projectSelect = { id: true, nombre: true, descripcion: true, estado: true, prioridad: true, creadoPorId: true, createdAt: true, updatedAt: true } as const;

@Injectable()
export class KairosService {
  constructor(private readonly prisma: PrismaService) {}

  private assertActive(actor: AuthUser) { if (actor.estado !== EstadoUsuario.ACTIVA) throw notFound("KAIROS_PROJECT_NOT_FOUND"); }
  private async membership(projectId: string, actorId: number) { return this.prisma.miembroProyectoKairos.findFirst({ where: { proyectoId: projectId, usuarioId: actorId, removedAt: null } }); }
  private async requireMember(projectId: string, actor: AuthUser) { this.assertActive(actor); const m = await this.membership(projectId, actor.id); if (!m) throw notFound("KAIROS_PROJECT_NOT_FOUND"); return m; }
  private canManage(role: RolMiembroProyectoKairos) { return role === RolMiembroProyectoKairos.PROPIETARIO || role === RolMiembroProyectoKairos.SUBLIDER; }
  private async audit(tx: any, actorId: number, action: string, subjectId: string, metadata?: unknown) { await tx.auditEvent.create({ data: { actorId, action, resource: "KAIROS_PROJECT", correlationId: subjectId, metadata: metadata as any } }); }

  async create(actor: AuthUser, input: ProjectInput) {
    this.assertActive(actor); const scope = getAccessScope(actor, Permission.KAIROS_PROJECT_CREATE); if (!scope) throw notFound("KAIROS_PROJECT_NOT_FOUND");
    return this.prisma.$transaction(async tx => { const p = await tx.proyectoKairos.create({ data: { ...input, descripcion: input.descripcion ?? null, creadoPorId: actor.id, miembros: { create: { usuarioId: actor.id, rol: RolMiembroProyectoKairos.PROPIETARIO } } }, select: projectSelect }); await this.audit(tx, actor.id, "CREATE", p.id); return p; });
  }

  async list(actor: AuthUser, page = 1, pageSize = 20, search?: string, favorite?: boolean) {
    this.assertActive(actor); const safePage = Math.min(Math.max(page || 1, 1), 10000); const take = Math.min(Math.max(pageSize || 20, 1), 100); const skip = (safePage - 1) * take;
    const where: any = { miembros: { some: { usuarioId: actor.id, removedAt: null } }, ...(search ? { nombre: { contains: search } } : {}), ...(favorite === true ? { favoritos: { some: { usuarioId: actor.id } } } : {}) };
    const [items, total] = await Promise.all([this.prisma.proyectoKairos.findMany({ where, select: { ...projectSelect, miembros: { where: { usuarioId: actor.id }, select: { rol: true } }, favoritos: { where: { usuarioId: actor.id }, select: { proyectoId: true } } }, orderBy: { updatedAt: "desc" }, skip, take }), this.prisma.proyectoKairos.count({ where })]);
    return { items: items.map((p: any) => ({ ...p, rol: p.miembros[0]?.rol, favorito: p.favoritos.length > 0, miembros: undefined, favoritos: undefined })), page: safePage, pageSize: take, total };
  }

  async get(actor: AuthUser, id: string) { return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${actor.id} AND removedAt IS NULL FOR UPDATE`; const m = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); const p = await tx.proyectoKairos.findUnique({ where: { id }, select: { ...projectSelect, miembros: { where: { removedAt: null, usuario: { estado: EstadoUsuario.ACTIVA } }, select: { usuarioId: true, rol: true, createdAt: true, usuario: { select: { id: true, codigo: true } } } }, favoritos: { where: { usuarioId: actor.id }, select: { proyectoId: true } } } }); if (!p || !m) throw notFound("KAIROS_PROJECT_NOT_FOUND"); return { ...p, rol: m.rol, favorito: p.favoritos.length > 0, favoritos: undefined }; }); }

  async update(actor: AuthUser, id: string, input: ProjectUpdate) { return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${actor.id} AND removedAt IS NULL FOR UPDATE`; const p0 = await tx.proyectoKairos.findUnique({ where: { id }, select: { estado: true } }); const m = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); if (!p0 || !m) throw notFound("KAIROS_PROJECT_NOT_FOUND"); if (p0.estado === EstadoProyectoKairos.ARCHIVADO || !this.canManage(m.rol)) throw notFound("KAIROS_PROJECT_NOT_FOUND"); const p = await tx.proyectoKairos.update({ where: { id }, data: input, select: projectSelect }); await this.audit(tx, actor.id, "UPDATE", id); return p; }); }

  async archive(actor: AuthUser, id: string) { return this.update(actor, id, { estado: EstadoProyectoKairos.ARCHIVADO }); }

  async addMember(actor: AuthUser, id: string, userId: number, rol: RolMiembroProyectoKairos) { if (rol === RolMiembroProyectoKairos.PROPIETARIO) throw invalidInput("KAIROS_TRANSFER_REQUIRED"); return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${actor.id} AND removedAt IS NULL FOR UPDATE`; const p = await tx.proyectoKairos.findUnique({ where: { id }, select: { estado: true } }); const m = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); if (!p || !m || p.estado === EstadoProyectoKairos.ARCHIVADO || !this.canManage(m.rol)) throw notFound("KAIROS_PROJECT_NOT_FOUND"); const user = await tx.usuario.findUnique({ where: { id: userId }, select: { id: true, estado: true } }); if (!user || user.estado !== EstadoUsuario.ACTIVA) throw invalidInput("KAIROS_MEMBER_INVALID"); const existing = await tx.miembroProyectoKairos.findUnique({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } } }); if (existing) { if (!existing.removedAt) throw conflict("KAIROS_MEMBER_EXISTS"); const reactivated = await tx.miembroProyectoKairos.update({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } }, data: { rol, removedAt: null } }); await this.audit(tx, actor.id, "REACTIVATE_MEMBER", id, { userId, rol }); return reactivated; } const member = await tx.miembroProyectoKairos.create({ data: { proyectoId: id, usuarioId: userId, rol } }); await this.audit(tx, actor.id, "ADD_MEMBER", id, { userId, rol }); return member; }); }

  async changeRole(actor: AuthUser, id: string, userId: number, rol: RolMiembroProyectoKairos) { return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${actor.id} AND removedAt IS NULL FOR UPDATE`; const p = await tx.proyectoKairos.findUnique({ where: { id }, select: { estado: true } }); const m = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); if (!p || !m || p.estado === EstadoProyectoKairos.ARCHIVADO || !this.canManage(m.rol)) throw notFound("KAIROS_PROJECT_NOT_FOUND"); const target = await tx.miembroProyectoKairos.findUnique({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } } }); if (!target || target.removedAt) throw notFound("KAIROS_MEMBER_NOT_FOUND"); if (target.rol === RolMiembroProyectoKairos.PROPIETARIO || rol === RolMiembroProyectoKairos.PROPIETARIO) throw conflict("KAIROS_TRANSFER_REQUIRED"); const updated = await tx.miembroProyectoKairos.update({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } }, data: { rol } }); await this.audit(tx, actor.id, "CHANGE_MEMBER_ROLE", id, { userId, rol }); return updated; }); }

  async transferOwnership(actor: AuthUser, id: string, userId: number) { if (actor.id === userId) throw invalidInput("KAIROS_TRANSFER_TARGET_INVALID"); return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; const first = Math.min(actor.id, userId); const second = Math.max(actor.id, userId); await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${first} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${second} FOR UPDATE`; const p = await tx.proyectoKairos.findUnique({ where: { id }, select: { estado: true } }); const current = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); const target = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: userId, removedAt: null, usuario: { estado: EstadoUsuario.ACTIVA } } }); if (!p || p.estado === EstadoProyectoKairos.ARCHIVADO || !current || current.rol !== RolMiembroProyectoKairos.PROPIETARIO || !target) throw notFound("KAIROS_PROJECT_NOT_FOUND"); await tx.miembroProyectoKairos.update({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: actor.id } }, data: { rol: RolMiembroProyectoKairos.SUBLIDER } }); const owner = await tx.miembroProyectoKairos.update({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } }, data: { rol: RolMiembroProyectoKairos.PROPIETARIO } }); await this.audit(tx, actor.id, "TRANSFER_OWNERSHIP", id, { fromUserId: actor.id, toUserId: userId }); return owner; }); }

  async removeMember(actor: AuthUser, id: string, userId: number) { return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${actor.id} AND removedAt IS NULL FOR UPDATE`; const p = await tx.proyectoKairos.findUnique({ where: { id }, select: { estado: true } }); const m = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); if (!p || !m || p.estado === EstadoProyectoKairos.ARCHIVADO || !this.canManage(m.rol)) throw notFound("KAIROS_PROJECT_NOT_FOUND"); const target = await tx.miembroProyectoKairos.findUnique({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } } }); if (!target || target.removedAt) throw notFound("KAIROS_MEMBER_NOT_FOUND"); if (target.rol === RolMiembroProyectoKairos.PROPIETARIO) throw conflict("KAIROS_OWNER_REQUIRED"); const updated = await tx.miembroProyectoKairos.update({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: userId } }, data: { removedAt: new Date() } }); await this.audit(tx, actor.id, "REMOVE_MEMBER", id, { userId }); return updated; }); }
  async favorite(actor: AuthUser, id: string, enabled: boolean) { return this.prisma.$transaction(async tx => { this.assertActive(actor); await tx.$executeRaw`SELECT id FROM ProyectoKairos WHERE id = ${id} FOR UPDATE`; await tx.$executeRaw`SELECT proyectoId FROM MiembroProyectoKairos WHERE proyectoId = ${id} AND usuarioId = ${actor.id} AND removedAt IS NULL FOR UPDATE`; const p = await tx.proyectoKairos.findUnique({ where: { id }, select: { id: true, estado: true } }); const m = await tx.miembroProyectoKairos.findFirst({ where: { proyectoId: id, usuarioId: actor.id, removedAt: null } }); if (!p || p.estado === EstadoProyectoKairos.ARCHIVADO || !m || actor.estado !== EstadoUsuario.ACTIVA) throw notFound("KAIROS_PROJECT_NOT_FOUND"); if (enabled) await tx.favoritoProyectoKairos.upsert({ where: { proyectoId_usuarioId: { proyectoId: id, usuarioId: actor.id } }, create: { proyectoId: id, usuarioId: actor.id }, update: {} }); else await tx.favoritoProyectoKairos.deleteMany({ where: { proyectoId: id, usuarioId: actor.id } }); await this.audit(tx, actor.id, "FAVORITE", id, { enabled }); return { id, favorito: enabled }; }); }
}
