CREATE TABLE `ReglaRetencion` (
  `id` VARCHAR(30) NOT NULL,
  `categoria` ENUM('IDENTIDAD_CUENTA','PERFIL_ACADEMICO','ASISTENCIA_HORAS','AUSENCIAS_JUSTIFICANTES','EXPEDIENTE','KAIROS_EVIDENCIAS','BIBLIOTECA','AUDITORIA','NOTIFICACIONES_CORREO','SESIONES_TOKENS','LOGS','EXPORTACIONES','ARCHIVOS_RECHAZADOS') NOT NULL,
  `version` INTEGER NOT NULL,
  `finalidad` VARCHAR(1000) NOT NULL,
  `responsable` VARCHAR(191) NOT NULL,
  `eventoInicio` VARCHAR(191) NOT NULL,
  `periodoActivoDias` INTEGER NOT NULL,
  `periodoBloqueadoDias` INTEGER NOT NULL,
  `accionFinal` ENUM('ELIMINAR','ANONIMIZAR') NOT NULL,
  `fundamento` VARCHAR(2000) NOT NULL,
  `provisional` BOOLEAN NOT NULL DEFAULT false,
  `automatica` BOOLEAN NOT NULL DEFAULT false,
  `estado` ENUM('BORRADOR','APROBADA','SUSTITUIDA') NOT NULL DEFAULT 'BORRADOR',
  `referenciaAprobacion` VARCHAR(500) NULL,
  `approvedAt` DATETIME(3) NULL,
  `creadoPorId` INTEGER NULL,
  `aprobadoPorId` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `ReglaRetencion_categoria_version_key`(`categoria`,`version`),
  INDEX `ReglaRetencion_categoria_estado_version_idx`(`categoria`,`estado`,`version`),
  PRIMARY KEY (`id`),
  CONSTRAINT `ReglaRetencion_creadoPorId_fkey` FOREIGN KEY (`creadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ReglaRetencion_aprobadoPorId_fkey` FOREIGN KEY (`aprobadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ReglaRetencion_periods_chk` CHECK (`version` > 0 AND `periodoActivoDias` >= 0 AND `periodoBloqueadoDias` >= 0),
  CONSTRAINT `ReglaRetencion_approval_chk` CHECK ((`estado` = 'APROBADA' AND `approvedAt` IS NOT NULL AND `aprobadoPorId` IS NOT NULL AND `referenciaAprobacion` IS NOT NULL) OR (`estado` <> 'APROBADA'))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `RegistroRetencion` (
  `id` VARCHAR(30) NOT NULL,
  `categoria` ENUM('IDENTIDAD_CUENTA','PERFIL_ACADEMICO','ASISTENCIA_HORAS','AUSENCIAS_JUSTIFICANTES','EXPEDIENTE','KAIROS_EVIDENCIAS','BIBLIOTECA','AUDITORIA','NOTIFICACIONES_CORREO','SESIONES_TOKENS','LOGS','EXPORTACIONES','ARCHIVOS_RECHAZADOS') NOT NULL,
  `resourceType` VARCHAR(100) NOT NULL,
  `resourceId` VARCHAR(191) NOT NULL,
  `subjectId` INTEGER NULL,
  `reglaId` VARCHAR(30) NOT NULL,
  `estado` ENUM('ACTIVO','BLOQUEADO_ARCHIVADO','SUPRESION_PROGRAMADA','SUPRIMIDO','ANONIMIZADO') NOT NULL DEFAULT 'ACTIVO',
  `triggeredAt` DATETIME(3) NOT NULL,
  `archiveDueAt` DATETIME(3) NOT NULL,
  `actionDueAt` DATETIME(3) NOT NULL,
  `blockedAt` DATETIME(3) NULL,
  `scheduledAt` DATETIME(3) NULL,
  `processedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `RegistroRetencion_categoria_resourceType_resourceId_key`(`categoria`,`resourceType`,`resourceId`),
  INDEX `RegistroRetencion_estado_actionDueAt_idx`(`estado`,`actionDueAt`),
  INDEX `RegistroRetencion_subjectId_estado_createdAt_idx`(`subjectId`,`estado`,`createdAt`),
  INDEX `RegistroRetencion_reglaId_estado_idx`(`reglaId`,`estado`),
  PRIMARY KEY (`id`),
  CONSTRAINT `RegistroRetencion_subjectId_fkey` FOREIGN KEY (`subjectId`) REFERENCES `Usuario`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `RegistroRetencion_reglaId_fkey` FOREIGN KEY (`reglaId`) REFERENCES `ReglaRetencion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `RegistroRetencion_dates_chk` CHECK (`archiveDueAt` >= `triggeredAt` AND `actionDueAt` >= `archiveDueAt`),
  CONSTRAINT `RegistroRetencion_terminal_chk` CHECK ((`estado` IN ('SUPRIMIDO','ANONIMIZADO') AND `processedAt` IS NOT NULL) OR (`estado` NOT IN ('SUPRIMIDO','ANONIMIZADO')))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `RetencionLegal` (
  `id` VARCHAR(30) NOT NULL,
  `registroId` VARCHAR(30) NOT NULL,
  `motivo` VARCHAR(2000) NOT NULL,
  `responsable` VARCHAR(191) NOT NULL,
  `reviewAt` DATETIME(3) NOT NULL,
  `endsAt` DATETIME(3) NULL,
  `estado` ENUM('ACTIVA','LIBERADA') NOT NULL DEFAULT 'ACTIVA',
  `creadoPorId` INTEGER NOT NULL,
  `liberadoPorId` INTEGER NULL,
  `motivoLiberacion` VARCHAR(2000) NULL,
  `releasedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `RetencionLegal_registroId_estado_reviewAt_idx`(`registroId`,`estado`,`reviewAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `RetencionLegal_registroId_fkey` FOREIGN KEY (`registroId`) REFERENCES `RegistroRetencion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `RetencionLegal_creadoPorId_fkey` FOREIGN KEY (`creadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `RetencionLegal_liberadoPorId_fkey` FOREIGN KEY (`liberadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `RetencionLegal_release_chk` CHECK ((`estado` = 'LIBERADA' AND `liberadoPorId` IS NOT NULL AND `motivoLiberacion` IS NOT NULL AND `releasedAt` IS NOT NULL) OR (`estado` = 'ACTIVA' AND `liberadoPorId` IS NULL AND `motivoLiberacion` IS NULL AND `releasedAt` IS NULL)),
  CONSTRAINT `RetencionLegal_review_chk` CHECK (`endsAt` IS NULL OR `endsAt` >= `reviewAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SolicitudSupresion` (
  `id` VARCHAR(30) NOT NULL,
  `solicitanteId` INTEGER NOT NULL,
  `motivo` VARCHAR(2000) NOT NULL,
  `estado` ENUM('ABIERTA','EN_REVISION','APROBADA','RECHAZADA','EJECUTADA') NOT NULL DEFAULT 'ABIERTA',
  `clasificacion` JSON NULL,
  `resolucion` VARCHAR(2000) NULL,
  `resueltoPorId` INTEGER NULL,
  `resolvedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `SolicitudSupresion_solicitanteId_createdAt_idx`(`solicitanteId`,`createdAt`),
  INDEX `SolicitudSupresion_estado_createdAt_idx`(`estado`,`createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `SolicitudSupresion_solicitanteId_fkey` FOREIGN KEY (`solicitanteId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SolicitudSupresion_resueltoPorId_fkey` FOREIGN KEY (`resueltoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `SolicitudSupresion_resolution_chk` CHECK ((`estado` IN ('APROBADA','RECHAZADA','EJECUTADA') AND `resueltoPorId` IS NOT NULL AND `resolucion` IS NOT NULL AND `resolvedAt` IS NOT NULL) OR (`estado` IN ('ABIERTA','EN_REVISION')))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LoteSupresion` (
  `id` VARCHAR(30) NOT NULL,
  `categoria` ENUM('IDENTIDAD_CUENTA','PERFIL_ACADEMICO','ASISTENCIA_HORAS','AUSENCIAS_JUSTIFICANTES','EXPEDIENTE','KAIROS_EVIDENCIAS','BIBLIOTECA','AUDITORIA','NOTIFICACIONES_CORREO','SESIONES_TOKENS','LOGS','EXPORTACIONES','ARCHIVOS_RECHAZADOS') NULL,
  `estado` ENUM('BORRADOR','AUTORIZADO','EN_EJECUCION','PAUSADO','COMPLETADO','FALLIDO') NOT NULL DEFAULT 'BORRADOR',
  `cutoffAt` DATETIME(3) NOT NULL,
  `totalElementos` INTEGER NOT NULL DEFAULT 0,
  `ejecutados` INTEGER NOT NULL DEFAULT 0,
  `omitidos` INTEGER NOT NULL DEFAULT 0,
  `fallidos` INTEGER NOT NULL DEFAULT 0,
  `creadoPorId` INTEGER NOT NULL,
  `autorizadoPorId` INTEGER NULL,
  `authorizedAt` DATETIME(3) NULL,
  `pausedAt` DATETIME(3) NULL,
  `motivoPausa` VARCHAR(1000) NULL,
  `startedAt` DATETIME(3) NULL,
  `finishedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `LoteSupresion_estado_createdAt_idx`(`estado`,`createdAt`),
  INDEX `LoteSupresion_categoria_estado_createdAt_idx`(`categoria`,`estado`,`createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `LoteSupresion_creadoPorId_fkey` FOREIGN KEY (`creadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `LoteSupresion_autorizadoPorId_fkey` FOREIGN KEY (`autorizadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `LoteSupresion_counts_chk` CHECK (`totalElementos` >= 0 AND `ejecutados` >= 0 AND `omitidos` >= 0 AND `fallidos` >= 0),
  CONSTRAINT `LoteSupresion_authorization_chk` CHECK ((`estado` = 'BORRADOR' AND `autorizadoPorId` IS NULL AND `authorizedAt` IS NULL) OR (`estado` <> 'BORRADOR' AND `autorizadoPorId` IS NOT NULL AND `authorizedAt` IS NOT NULL))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ElementoLoteSupresion` (
  `id` VARCHAR(30) NOT NULL,
  `loteId` VARCHAR(30) NOT NULL,
  `registroId` VARCHAR(30) NOT NULL,
  `estado` ENUM('PENDIENTE','PROCESANDO','OMITIDO_RETENCION_LEGAL','EJECUTADO','FALLIDO') NOT NULL DEFAULT 'PENDIENTE',
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `nextAttemptAt` DATETIME(3) NULL,
  `leaseUntil` DATETIME(3) NULL,
  `leaseOwner` VARCHAR(80) NULL,
  `errorCode` VARCHAR(100) NULL,
  `processedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `ElementoLoteSupresion_loteId_registroId_key`(`loteId`,`registroId`),
  INDEX `ElementoLoteSupresion_loteId_estado_idx`(`loteId`,`estado`),
  INDEX `ElementoLoteSupresion_estado_nextAttemptAt_leaseUntil_idx`(`estado`,`nextAttemptAt`,`leaseUntil`),
  PRIMARY KEY (`id`),
  CONSTRAINT `ElementoLoteSupresion_loteId_fkey` FOREIGN KEY (`loteId`) REFERENCES `LoteSupresion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ElementoLoteSupresion_registroId_fkey` FOREIGN KEY (`registroId`) REFERENCES `RegistroRetencion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ElementoLoteSupresion_attempts_chk` CHECK (`attempts` >= 0),
  CONSTRAINT `ElementoLoteSupresion_processed_chk` CHECK ((`estado` IN ('PENDIENTE','PROCESANDO') AND `processedAt` IS NULL) OR (`estado` NOT IN ('PENDIENTE','PROCESANDO') AND `processedAt` IS NOT NULL)),
  CONSTRAINT `ElementoLoteSupresion_lease_chk` CHECK ((`estado` = 'PROCESANDO' AND `leaseUntil` IS NOT NULL AND `leaseOwner` IS NOT NULL) OR (`estado` <> 'PROCESANDO' AND `leaseUntil` IS NULL AND `leaseOwner` IS NULL))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `RegistroSupresion` (
  `id` VARCHAR(30) NOT NULL,
  `registroId` VARCHAR(30) NOT NULL,
  `categoria` ENUM('IDENTIDAD_CUENTA','PERFIL_ACADEMICO','ASISTENCIA_HORAS','AUSENCIAS_JUSTIFICANTES','EXPEDIENTE','KAIROS_EVIDENCIAS','BIBLIOTECA','AUDITORIA','NOTIFICACIONES_CORREO','SESIONES_TOKENS','LOGS','EXPORTACIONES','ARCHIVOS_RECHAZADOS') NOT NULL,
  `resourceType` VARCHAR(100) NOT NULL,
  `resourceFingerprint` CHAR(64) NOT NULL,
  `accion` ENUM('ELIMINAR','ANONIMIZAR') NOT NULL,
  `policyVersion` INTEGER NOT NULL,
  `loteId` VARCHAR(30) NOT NULL,
  `ejecutadoPorId` INTEGER NULL,
  `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastReappliedAt` DATETIME(3) NULL,
  UNIQUE INDEX `RegistroSupresion_registroId_accion_key`(`registroId`,`accion`),
  INDEX `RegistroSupresion_categoria_occurredAt_idx`(`categoria`,`occurredAt`),
  INDEX `RegistroSupresion_loteId_occurredAt_idx`(`loteId`,`occurredAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `RegistroSupresion_registroId_fkey` FOREIGN KEY (`registroId`) REFERENCES `RegistroRetencion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `RegistroSupresion_ejecutadoPorId_fkey` FOREIGN KEY (`ejecutadoPorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `OperacionRetencion` (
  `id` VARCHAR(30) NOT NULL,
  `actorId` INTEGER NOT NULL,
  `key` VARCHAR(128) NOT NULL,
  `requestHash` CHAR(64) NOT NULL,
  `tipo` ENUM('CREAR_REGLA','APROBAR_REGLA','REGISTRAR_ELEMENTO','CREAR_RETENCION_LEGAL','LIBERAR_RETENCION_LEGAL','CREAR_SOLICITUD','RESOLVER_SOLICITUD','CREAR_LOTE','AUTORIZAR_LOTE','PAUSAR_LOTE','EJECUTAR_LOTE','REAPLICAR_SUPRESIONES') NOT NULL,
  `loteId` VARCHAR(30) NULL,
  `response` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `OperacionRetencion_actorId_key_key`(`actorId`,`key`),
  INDEX `OperacionRetencion_loteId_createdAt_idx`(`loteId`,`createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `OperacionRetencion_actorId_fkey` FOREIGN KEY (`actorId`) REFERENCES `Usuario`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `OperacionRetencion_loteId_fkey` FOREIGN KEY (`loteId`) REFERENCES `LoteSupresion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
