import { Injectable } from "@nestjs/common";
import { PrismaService } from "../database/prisma.service";
import { EstadoArchivo, EstadoDocumento, EstadoUsuario } from "../generated/prisma/enums";
import { AccessScope, getAccessScope, Permission } from "../auth/permissions";
import type { AuthUser } from "../auth/auth-user";
import { conflict, invalidInput, notFound } from "../common/errors/domain-error";
import { issueDownloadCapability } from "../storage/storage.types";
import { StorageService } from "../storage/storage.service";
import type { RequirementInput, ReviewInput, UploadInput } from "./documents.schemas";
import { AuditService } from "../auth/audit.service";

@Injectable()
export class DocumentsService {
  constructor(private readonly prisma: PrismaService, private readonly storage: StorageService, private readonly audit: AuditService = null as any) {}
  private scope(actor: AuthUser) { if (actor.estado !== EstadoUsuario.ACTIVA) throw notFound("DOCUMENT_NOT_FOUND"); return getAccessScope(actor, Permission.DOCUMENTS_READ) ?? AccessScope.SELF; }
  private async target(id: number) { const r = await this.prisma.requisitoDocumento.findUnique({ where: { id }, include: { usuario: { select: { id: true, sedeId: true, areaId: true, estado: true } } } }); if (!r || !r.activo || r.usuario.estado !== EstadoUsuario.ACTIVA) throw notFound("DOCUMENT_NOT_FOUND"); return r; }
  private allowed(actor: AuthUser, user: { id: number; sedeId: number | null; areaId: number | null }) { const s = this.scope(actor); return s === AccessScope.GLOBAL || (s === AccessScope.SEDE && actor.sedeId === user.sedeId) || (s === AccessScope.AREA && actor.areaId === user.areaId) || (s === AccessScope.SELF && actor.id === user.id); }
  async createRequirement(actor: AuthUser, input: RequirementInput) { if (this.scope(actor) !== AccessScope.GLOBAL) throw invalidInput("DOCUMENT_REQUIREMENT_NOT_ALLOWED"); const target = await this.prisma.usuario.findUnique({ where: { id: input.usuarioId }, select: { id: true, rol: true, estado: true } }); if (!target || target.estado !== EstadoUsuario.ACTIVA || target.rol !== "PRESTADOR") throw notFound("DOCUMENT_NOT_FOUND"); return this.prisma.$transaction(async tx => { const created = await tx.requisitoDocumento.create({ data: { usuarioId: target.id, codigo: input.codigo, nombre: input.nombre, obligatorio: input.obligatorio } }); await this.audit.append({ actorId: actor.id, subjectId: target.id, action: "DOCUMENT_REQUIREMENT_CREATED", resource: "document_requirement", correlationId: String(created.id), metadata: { result: "created" } }, tx); return created; }); }
  async list(actor: AuthUser, userId = actor.id, page = 1, pageSize = 50) { const target = await this.prisma.usuario.findUnique({ where: { id: userId }, select: { id: true, sedeId: true, areaId: true, estado: true } }); if (!target || target.estado !== EstadoUsuario.ACTIVA || !this.allowed(actor, target)) throw notFound("DOCUMENT_NOT_FOUND"); const take = Math.min(Math.max(pageSize, 1), 100), skip = (Math.max(page, 1) - 1) * take; const where = { usuarioId: userId, activo: true }; const [items, total] = await Promise.all([this.prisma.requisitoDocumento.findMany({ where, select: { id: true, usuarioId: true, codigo: true, nombre: true, obligatorio: true, activo: true, createdAt: true, updatedAt: true, versiones: { orderBy: { version: "desc" }, take: 1, select: { id: true, version: true, estado: true, comentario: true, createdAt: true, updatedAt: true, archivo: { select: { id: true, originalName: true, detectedMime: true, sizeBytes: true, status: true, createdAt: true, updatedAt: true } } } } }, orderBy: { id: "asc" }, skip, take }), this.prisma.requisitoDocumento.count({ where })]); return { items, total, page: Math.max(page, 1), pageSize: take }; }
  async upload(actor: AuthUser, input: UploadInput) { const req = await this.target(input.requisitoId); if (actor.id !== req.usuarioId) throw notFound("DOCUMENT_NOT_FOUND"); const file = await this.prisma.archivo.findUnique({ where: { id: input.archivoId } }); if (!file || file.status !== EstadoArchivo.DISPONIBLE || !["application/pdf", "image/jpeg", "image/png"].includes(file.detectedMime ?? "")) throw invalidInput("DOCUMENT_FILE_NOT_AVAILABLE"); return this.prisma.$transaction(async tx => { await tx.$executeRaw`SELECT id FROM RequisitoDocumento WHERE id = ${req.id} FOR UPDATE`; const pending = await tx.documentoVersion.findFirst({ where: { requisitoId: req.id, estado: { in: [EstadoDocumento.EN_REVISION, EstadoDocumento.PENDIENTE_CARGA] } } }); if (pending) throw conflict("DOCUMENT_PENDING_VERSION_EXISTS"); const latest = await tx.documentoVersion.findFirst({ where: { requisitoId: req.id }, orderBy: { version: "desc" } }); const created = await tx.documentoVersion.create({ data: { requisitoId: req.id, archivoId: file.id, version: (latest?.version ?? 0) + 1, estado: EstadoDocumento.EN_REVISION, cargadoPorId: actor.id } }); await this.audit.append({ actorId: actor.id, subjectId: req.usuarioId, action: "DOCUMENT_VERSION_UPLOADED", resource: "document_version", correlationId: created.id, metadata: { result: "created", version: created.version } }, tx); return created; }); }
  async review(actor: AuthUser, id: string, input: ReviewInput) { const item = await this.prisma.documentoVersion.findUnique({ where: { id }, include: { requisito: { include: { usuario: { select: { id: true, sedeId: true, areaId: true, estado: true } } } } } }); if (!item || item.requisito.usuario.estado !== EstadoUsuario.ACTIVA || !this.allowed(actor, item.requisito.usuario) || actor.id === item.cargadoPorId) throw notFound("DOCUMENT_NOT_FOUND"); if (item.estado !== EstadoDocumento.EN_REVISION) throw conflict("DOCUMENT_ALREADY_REVIEWED"); return this.prisma.$transaction(async tx => { await tx.$executeRaw`SELECT id FROM DocumentoVersion WHERE id = ${id} FOR UPDATE`; const locked = await tx.documentoVersion.findUnique({ where: { id } }); if (!locked || locked.estado !== EstadoDocumento.EN_REVISION) throw conflict("DOCUMENT_ALREADY_REVIEWED"); const updated = await tx.documentoVersion.update({ where: { id }, data: { estado: input.estado as EstadoDocumento, comentario: input.comentario ?? null, revisadoPorId: actor.id } }); await this.audit.append({ actorId: actor.id, subjectId: item.requisito.usuario.id, action: "DOCUMENT_VERSION_REVIEWED", resource: "document_version", correlationId: id, metadata: { result: input.estado } }, tx); return updated; }); }
  async download(actor: AuthUser, id: string) { const item = await this.prisma.documentoVersion.findUnique({ where: { id }, select: { archivoId: true, estado: true, requisito: { select: { usuario: { select: { id: true, sedeId: true, areaId: true, estado: true } } } } } }); if (!item || item.requisito.usuario.estado !== EstadoUsuario.ACTIVA || !this.allowed(actor, item.requisito.usuario) || item.estado !== EstadoDocumento.AUTORIZADO) throw notFound("DOCUMENT_NOT_FOUND"); await this.audit.append({ actorId: actor.id, subjectId: item.requisito.usuario.id, action: "DOCUMENT_DOWNLOAD_REQUESTED", resource: "document_version", correlationId: id, metadata: { result: "authorized" } }); return this.storage.downloadUrl(item.archivoId, issueDownloadCapability({ subjectId: String(actor.id), resourceId: item.archivoId, purpose: "download", issuedAt: new Date() }), String(actor.id)); }
}
