import { BadRequestException, Inject, Injectable, NotFoundException, ServiceUnavailableException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { createHash, randomUUID } from "node:crypto";
import { Readable } from "node:stream";
import { createReadStream, createWriteStream } from "node:fs";
import { open, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, extname, join } from "node:path";
import { TextDecoder } from "node:util";
import { PrismaService } from "../database/prisma.service";
import { EstadoArchivo } from "../generated/prisma/enums";
import type { Environment } from "../config/environment";
import type { DownloadCapability, MalwareScanner } from "./storage.types";
import { S3Storage } from "./s3.storage";

const extensionMime: Record<string,string> = { ".pdf":"application/pdf", ".jpg":"image/jpeg", ".jpeg":"image/jpeg", ".png":"image/png", ".txt":"text/plain", ".stl":"model/stl" };
@Injectable()
export class StorageService {
  constructor(private readonly prisma: PrismaService, private readonly storage: S3Storage, @Inject("MALWARE_SCANNER") private readonly scanner: MalwareScanner, private readonly config: ConfigService<Environment,true>) {}
  async receive(input:{originalName:string;contentType?:string;body:Buffer|Readable|AsyncIterable<Buffer>;sizeBytes?:number}) {
    const max=this.config.get("STORAGE_MAX_BYTES"); const name=basename(input.originalName);
    if(!name||name!==input.originalName||/\.[^.]+\.[^.]+$/.test(name)||/[\\/]/.test(input.originalName)) throw new BadRequestException("Nombre de archivo no permitido");
    if(input.sizeBytes!==undefined&&(input.sizeBytes<=0||input.sizeBytes>max)) throw new BadRequestException("Archivo vacío o excede el tamaño permitido");
    const dir=await mkdtemp(join(tmpdir(),"ares-upload-")), path=join(dir,"payload"); let size=0; const hash=createHash("sha256");
    try { const out=createWriteStream(path,{mode:0o600}); const source=Buffer.isBuffer(input.body)?Readable.from([input.body]):input.body as AsyncIterable<Buffer>;
      try { for await(const chunk of source){const b=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk); size+=b.length; if(size>max) throw new BadRequestException("Archivo vacío o excede el tamaño permitido"); hash.update(b); if(!out.write(b)) await new Promise<void>((resolve,reject)=>{out.once("drain",resolve);out.once("error",reject);});} await new Promise<void>((resolve,reject)=>{out.once("error",reject);out.end(resolve);}); } catch(e){out.destroy();throw e;}
      if(!size||(input.sizeBytes!==undefined&&input.sizeBytes!==size)) throw new BadRequestException("El tamaño declarado no coincide con el contenido");
      const detected=await this.detectMime(path,size,input.contentType), ext=extname(name).toLowerCase(); if(extensionMime[ext]!==detected) throw new BadRequestException("La extensión no coincide con el tipo de archivo"); if(input.contentType&&input.contentType!==detected) throw new BadRequestException("Tipo de archivo no coincide con su firma");
      const digest=hash.digest("hex"), id=randomUUID(), key=`${id}/${digest}`; const file=await this.prisma.archivo.create({data:{id,objectKey:key,quarantineKey:key,originalName:name.slice(0,255),detectedMime:detected,extension:ext.slice(1),sizeBytes:size,sha256:digest,status:EstadoArchivo.PENDIENTE_ANALISIS}});
      try{await this.storage.put("quarantine",key,createReadStream(path),detected);}catch(error){await this.prisma.archivo.update({where:{id},data:{status:EstadoArchivo.ELIMINADO,lastError:this.safeError(error)}});throw error;} return file;
    } finally { await rm(dir,{recursive:true,force:true}); }
  }
  private async detectMime(path:string,size:number,claimed?:string){const head=await this.readRange(path,0,Math.min(size,16)); if(head.subarray(0,5).toString()==="%PDF-"){const tail=await this.readRange(path,Math.max(0,size-1024),size);if(!tail.includes(Buffer.from("%%EOF")))throw new BadRequestException("PDF truncado");return "application/pdf";} if(head[0]===0xff&&head[1]===0xd8){const tail=await this.readRange(path,Math.max(0,size-2),size);if(tail.length!==2||tail[0]!==0xff||tail[1]!==0xd9)throw new BadRequestException("JPEG truncado");return "image/jpeg";} if(head[0]===0x89&&head[1]===0x50&&head[2]===0x4e&&head[3]===0x47&&head[4]===0x0d&&head[5]===0x0a&&head[6]===0x1a&&head[7]===0x0a){const tail=await this.readRange(path,Math.max(0,size-12),size);if(!tail.includes(Buffer.from("IEND")))throw new BadRequestException("PNG truncado");return "image/png";} if(head[0]===0x50&&head[1]===0x4b)throw new BadRequestException("Contenedores ZIP no permitidos"); if(claimed==="model/stl"){if(await this.validBinaryStl(path,size)||await this.validAsciiStl(path))return "model/stl";throw new BadRequestException("Firma STL no válida");} if(claimed==="text/plain"){if(await this.validText(path))return "text/plain";throw new BadRequestException("Texto UTF-8 no válido");} throw new BadRequestException("Firma de archivo no válida");}
  private async readRange(path:string,start:number,end:number){const fh=await open(path,"r");try{const b=Buffer.alloc(Math.max(0,end-start));const n=(await fh.read(b,0,b.length,start)).bytesRead;return b.subarray(0,n);}finally{await fh.close();}}
  private async validText(path:string){const d=new TextDecoder("utf-8",{fatal:true});try{for await(const chunk of createReadStream(path)){for(const c of d.decode(chunk as Buffer,{stream:true})){const n=c.charCodeAt(0);if(!(n===9||n===10||n===13||(n>=32&&n!==127)))return false;}}for(const c of d.decode()){const n=c.charCodeAt(0);if(!(n===9||n===10||n===13||(n>=32&&n!==127)))return false;}return true;}catch{return false;}}
  private async validAsciiStl(path:string){let state="start",vertices:number[][]=[],facets=0,end=false,carry="";const consume=(t:string)=>{t=t.trim();if(!t)return true;if(state==="start"&&/^solid(?:\s|$)/i.test(t)){state="facet";return true;}if(state==="facet"&&/^facet\s+normal\s+([-+]?\d*\.?\d+(?:e[-+]?\d+)?)\s+([-+]?\d*\.?\d+(?:e[-+]?\d+)?)\s+([-+]?\d*\.?\d+(?:e[-+]?\d+)?)$/i.test(t)){state="outer";vertices=[];return true;}if(state==="outer"&&/^outer\s+loop$/i.test(t)){state="vertices";return true;}if(state==="vertices"&&/^vertex\s+([-+]?\d*\.?\d+(?:e[-+]?\d+)?)\s+([-+]?\d*\.?\d+(?:e[-+]?\d+)?)\s+([-+]?\d*\.?\d+(?:e[-+]?\d+)?)$/i.test(t)){vertices.push(t.split(/\s+/).slice(1).map(Number));return true;}if(state==="vertices"&&/^endloop$/i.test(t)&&vertices.length===3){const[a,b,c]=vertices,u=b.map((v,i)=>v-a[i]),v=c.map((x,i)=>x-a[i]),area=(u[1]*v[2]-u[2]*v[1])**2+(u[2]*v[0]-u[0]*v[2])**2+(u[0]*v[1]-u[1]*v[0])**2;if(!Number.isFinite(area)||area<=1e-20)return false;state="endfacet";return true;}if(state==="endfacet"&&/^endfacet$/i.test(t)){facets++;state="facet";return true;}if(state==="facet"&&/^endsolid(?:\s|$)/i.test(t)){end=true;state="done";return true;}return state==="done";};for await(const raw of createReadStream(path,{encoding:"utf8"})){const lines=(carry+raw).split(/\r?\n/);carry=lines.pop()??"";for(const line of lines)if(!consume(line))return false;}if(carry&&!consume(carry))return false;return end&&facets>0&&state==="done";}
  private async validBinaryStl(path:string,size:number){if(size<84)return false;const fh=await open(path,"r");try{const header=Buffer.alloc(84);if((await fh.read(header,0,84,0)).bytesRead!==84)return false;const count=header.readUInt32LE(80);if(!count||84+count*50!==size)return false;const r=Buffer.alloc(50);for(let index=0;index<count;index++){if((await fh.read(r,0,50,84+index*50)).bytesRead!==50)return false;const v=Array.from({length:9},(_,j)=>r.readFloatLE(12+j*4));if(v.some(x=>!Number.isFinite(x)))return false;const[a,b,c,d,e,f,g,h1,i]=v;const u=[d-a,e-b,f-c],w=[g-a,h1-b,i-c],area=(u[1]*w[2]-u[2]*w[1])**2+(u[2]*w[0]-u[0]*w[2])**2+(u[0]*w[1]-u[1]*w[0])**2;if(area<=1e-20)return false;}return true;}finally{await fh.close();}}
  async analyze(id:string,owner?:string){const file=await this.prisma.archivo.findUnique({where:{id}});if(!file)throw new NotFoundException("Archivo no encontrado");if(owner&&(file.leaseOwner!==owner||file.status!==EstadoArchivo.ANALIZANDO||!file.leaseUntil||file.leaseUntil<=new Date()))return file;try{const result=await this.scanner.scan(await this.storage.get("quarantine",file.quarantineKey));await this.prisma.analisisArchivo.create({data:{archivoId:id,scanner:"clamav",resultado:result.clean?"LIMPIO":"INFECTADO",signature:result.signature,finishedAt:new Date()}});if(!result.clean){await this.storage.delete("quarantine",file.quarantineKey);await this.prisma.archivo.updateMany({where:{id,leaseOwner:owner,status:EstadoArchivo.ANALIZANDO,leaseUntil:{gt:new Date()}},data:{status:EstadoArchivo.RECHAZADO,lastError:result.signature,leaseOwner:null,leaseUntil:null}});return this.prisma.archivo.findUnique({where:{id}});}await this.storage.copy("quarantine","available",file.quarantineKey);const promoted=await this.prisma.archivo.updateMany({where:{id,leaseOwner:owner,status:EstadoArchivo.ANALIZANDO,leaseUntil:{gt:new Date()}},data:{status:EstadoArchivo.DISPONIBLE,objectKey:file.quarantineKey,leaseOwner:null,leaseUntil:null}});if(!promoted.count){try{await this.storage.delete("available",file.quarantineKey);}catch{}return this.prisma.archivo.findUnique({where:{id}});}try{await this.storage.delete("quarantine",file.quarantineKey);}catch{}return this.prisma.archivo.findUnique({where:{id}});}catch(error){const safe=this.safeError(error);await this.prisma.analisisArchivo.create({data:{archivoId:id,scanner:"clamav",resultado:"ERROR",error:safe,finishedAt:new Date()}});await this.prisma.archivo.updateMany({where:{id,leaseOwner:owner,status:EstadoArchivo.ANALIZANDO,leaseUntil:{gt:new Date()}},data:{status:EstadoArchivo.ERROR_ANALISIS,lastError:safe,nextAttemptAt:new Date(Date.now()+60000),leaseOwner:null,leaseUntil:null}});return this.prisma.archivo.findUnique({where:{id}});}}
  private safeError(error:unknown){const code=typeof error==="object"&&error&&"name"in error?String((error as{name?:unknown}).name):"StorageError";return code.replace(/[^A-Za-z0-9_.-]/g,"").slice(0,120);}
  async downloadUrl(id:string,capability:DownloadCapability,currentSubjectId:string){if(!capability||capability.subjectId!==currentSubjectId||capability.resourceId!==id||capability.purpose!=="download"||!(capability.issuedAt instanceof Date)||Date.now()-capability.issuedAt.getTime()>300000)throw new ServiceUnavailableException("Descarga no autorizada");const file=await this.prisma.archivo.findUnique({where:{id}});if(!file||file.status!==EstadoArchivo.DISPONIBLE)throw new ServiceUnavailableException("Archivo no disponible");return this.storage.signedDownload(file.objectKey,300,file.originalName,file.detectedMime??"application/octet-stream");}
}
